version: '3.5'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    #   MONGO_INITDB_DATABASE: users

  mongo-seed:
    container_name: mongo-seed
    build: ./mongo-seed
    links:
      - mongo
  
  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - mongodb